pipeline {
    agent {
        label 'agent-1'
    }
    options {
        // Timeout counter starts BEFORE agent is allocated
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
        //retry(1)
    }
    parameters {
        
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')

    
    }
    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1' , credentials: 'as-creds'){
                sh """
                    cd 10-vpc
                    terraform init -reconfigure
                
                    terraform plan -out=tfplan
                """
                }    
            
        }
            }
        stage('apply or destroy') {
             steps {
                withAWS(region: 'us-east-1' , credentials: 'as-creds'){
                sh """
                    cd 10-vpc
                    if[ ${params.ACTION} == 'apply' ]
                    then
                    terraform apply -auto-approve tfplan
                    elif [ ${params.ACTION} == 'destroy' ]
                    then
                    terraform destroy -auto-approve
                    fi
                
    
                """
                }    
            
        }
            }
    }
        // stage('Test') {
        //     steps { 
        //         sh "echo this is test"
        //     }
        // }
        // stage('Deploy') {
        //     when{

        //         expression {env.GIT_BRANCH != 'origin/main'}
        //     }
        //     steps {
        //         sh "echo this is deploy"
        //         //error "pipeline failed"
        //     }
        // }
        // stage('print params'){
        //     steps{
        //         echo "Hello ${params.PERSON}"

        //         echo "Biography: ${params.BIOGRAPHY}"

        //         echo "Toggle: ${params.TOGGLE}"

        //         echo "Choice: ${params.CHOICE}"

        //         echo "Password: ${params.PASSWORD}"
        //     } 
        // }

       
    

    post {
        always {
            echo "this section runs always"
            deleteDir()
        }

        success {

            echo "this section runs when pipeline success"
        }

        failure {
            echo "this section runs when pipeline fails"
        }
    }
}
